# Server Configuration
server.port=8080

# MongoDB Configuration (Hardcoded for testing)
spring.mongodb.uri=mongodb+srv://ihthishamirshad:Ihthisham_781@primecluster.krthxls.mongodb.net/smart-campus?retryWrites=true&w=majority&appName=PrimeCluster

# Ensure Spring Boot doesn't fail if collections don't exist yet
spring.data.mongodb.auto-index-creation=true
